### ISSUE TITLE
Error message 'No such file or directory: 'asvtemp_unaligned.fa''

### ISSUE THREAD

**Issue by BWobbii** [tjcreedy/numtdumper#1]
Hi!
I've run metaMATE in `find` mode first, specifications:  `[library; p; 0.00025-0.01/20] +  [library; p;  0.001-0.007/7]`

I decided on one of the thresholds and ran metaMATE in `dump` mode, using this command:

`metamate dump -A all_sh.fasta -C outputdir/all_sh_resultcache -i 20 -o out_filtered`

I'm getting this error message:

`Welcome to metaMATE, let's dump!
Read 1299 ASVs.
Read 1 cached results.
Writing fastas for 1 results...done.
Traceback (most recent call last):
  File "/home/sickel/.local/bin/metamate", line 11, in <module>
    sys.exit(main())
  File "/home/sickel/.local/lib/python3.6/site-packages/metamate/metamate.py", line 401, in main
    os.remove('asvtemp_unaligned.fa')
FileNotFoundError: [Errno 2] No such file or directory: 'asvtemp_unaligned.fa' `

It's clearly looking for the temporal file of unaligned ASVs, which I guess it did not create, because I didn't have aligned ASVs as an input?
It did create an `aligned.fa` file, but now seems to look for an unaligned file as well...

Further, I have a txt-file in my output (no extension), which does look like a fasta-file and is smaller than my input fasta-file, so apparently some filtering has happened?
Has metaMATE run successfull although I'm getting the error?

Thanks a lot in advance!

**Comment by morien** [comment]
I got this error as well. It looks like it doesn't interfere with the creation of the filtered output fasta, so it might just be coming up because there's no exception in the code for if you have no ASVs that don't align.

**Comment by johnrandallia** [comment]
Hey,
The bug is fixed in more recent versions of metamate on github. We will update the pip version soon.
Cheers
