### ISSUE TITLE
Explnanation on "refpass" in find output file

### ISSUE THREAD

**Issue by naurasd** [tjcreedy/numtdumper#7]
Hi @tjcreedy 

I am having trouble understanding what the ASVs classified as "refpass" in the "..._control.txt" file of the `find` output are? So apparently they matched an entry in a supplied database with 100% query cover and 100% similarity and passed the length and translation thresholds. Is that all? Or is there any further meaning why specifically these ASVs are listed in the output?

Cheers
Nauras

**Comment by johnrandallia** [comment]
Hi Nauras,
your assumption is correct.  
ASVs are labelled with refpass if they match with one of the provided reference sequences and don't get sorted out due to frameshift or a different sequence length. 
Cheers,
Marius
